### ISSUE TITLE
Memory leak với ibus-bogo và auto_corrector/enchant

### ISSUE THREAD

**Issue by Funnnny** [BoGoEngine/ibus-bogo#222]
Trong ibus_engine.py, auto_corrector được tạo mới mỗi lần tạo engine, dẫn đến việc sau 1 thời gian dài sử dụng, bogo sẽ chiếm rất nhiều dung lượng RAM.

Có thể test behaviour này bằng cách lấy 1 text box trong Chrome và copy/paste 1 đoạn text liên tục, ibus-bogo sẽ nhanh chóng ăn khoảng 200-400MB Ram.

Giải pháp có thể là move việc init auto_corrector trong ibus_engine vào main và chỉ dùng 1 instance đó cho tất cả các engine

**Comment by Thik** [comment]
+1, critical bug

**Comment by cmpitg** [comment]
@fuzzysource Ping.

**Comment by Funnnny** [comment]
https://github.com/Funnnny/ibus-bogo/commit/ade6c992145ae547c9c7d694e2e76ff81af0e89c
Thế này có thể là chính xác, nếu project còn maintaint thì mình sẽ tạo PR?

**Comment by cmpitg** [comment]
@Funnnny Bạn tạo PR đi. Mình hoặc @fuzzysource sẽ review rồi merge.
