### ISSUE TITLE
Ibus-Bogo không hoạt động trên Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by 5cmpersec** [BoGoEngine/ibus-bogo#225]
Chào mọi người, cho phép mình report lỗi nhé
[Lỗi]
Ibus-Bogo không hoạt động trên Ubuntu 14.04 LTS
[Cấu hình]
Ubuntu 14.04 LTS 64bit
Cài đặt từ mã nguồn
[Tần suất xảy ra]
100%
[Reference]
Ibus-Unikey hoạt động ổn
[Đính kèm]
N/A
[Yêu cầu]
Sửa lỗi càng sớm càng tốt. Xin cảm ơn.

**Comment by cmpitg** [comment]
@lewtds Ping

**Comment by lewtds** [comment]
@5cmpersec Bạn có thể xem log bằng cách chạy trực tiếp file executable của ibus-bogo, không khởi động bằng ibus.

```
$ python3 /usr/share/ibus-bogo/ibus_engine/main.py
```

Hiện tại dự án đang ngừng phát triển do gặp trở ngại lớn về kỹ thuật. Bạn có thể đọc bài viết sau để hiểu thêm. 

http://ngochin.com/2014/07/31/uoc-mo-bo-go-kieu-unikey/

Issue này sẽ tạm đóng.

**Comment by 5cmpersec** [comment]
Hi,

@lewtds @cmpitg  Cảm ơn những phản hồi của các bạn.
Chúc dự án có những bước phát triển mới.

BR.
