### ISSUE TITLE
Dvorak Compatible

### ISSUE THREAD

**Issue by DungxNguyen** [BoGoEngine/ibus-bogo#235]
Could you guy make it compatible with Dvorak layout please?

**Comment by NgoHuy** [comment]
I use Dvorak without issues, it's problem of ibus, not bogo, bro

**Comment by DungxNguyen** [comment]
How could you change the layout of keyboard to ibus-bogo from Dvorak? Usually, I use Dvorak layout and when i change to ibus-bogo, the system layout becomes Qwerty. It doesn't happen if i change from Dvorak to m17n engine.

**Comment by NgoHuy** [comment]
just set dvorak as system layout

**Comment by DungxNguyen** [comment]
How do you set it? I chose Dvorak layout when I installed the system and nothing changed then.

**Comment by NgoHuy** [comment]
`$: cat /etc/X11/xorg.conf.d/10-edev.conf
Section "InputClass"
        Identifier "evdev keyboard catchall"
        MatchIsKeyboard "on"
        MatchDevicePath "/dev/input/event*"
        Driver "evdev"
        Option "XkbLayout" "dvorak"
        #Option "XkbVariant" "dvorak"
EndSection
`

**Comment by DungxNguyen** [comment]
This is my file:
# Read and parsed by systemd-localed. It's probably wise not to edit this file
# manually too freely.
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "us"
        Option "XkbVariant" "dvorak"
EndSection

**Comment by cmpitg** [comment]
@DungxNguyen: Does the `Use system keyboard layout` in `ibus-setup` work for you?

![iBus setup dialog](https://camo.githubusercontent.com/e178eb559ad29156e9521bde180ab5b2ff7e0ec4/687474703a2f2f692e696d6775722e636f6d2f59336a664d774e2e6a7067)

**Comment by DungxNguyen** [comment]
I select the option. However everything is the same.

The version of ibus is 1.5.11, ibus-bogo is 0.4. 

![screenshot from 2015-12-28 17-32-30](https://cloud.githubusercontent.com/assets/3928909/12017441/16b13792-ad89-11e5-97bf-497c4a9d7f11.png)

**Comment by cmpitg** [comment]
Are you using Ubuntu 15.10? If it's the case, would you mind downgrading iBus to see if the problem persists. iBus in Ubuntu 15.04+ doesn't respect system keyboard layout.

**Comment by DungxNguyen** [comment]
I'm using Fedora 23. As far as i know, Ibus has been integrated in to Gnome Shell for several gnome release. The problem also happens with Arch Linux. 
I have a workaround solution that after changing to Ibus-bogo method, run the command "setxkbmap -model pc104 -layout us  -variant dvorak". Changing to ibus-bogo somehow set the layout to qwerty.
However, Vietnamese m17n ibus engine has not been affected. Changing from Dvorak to m17n keeps dvorak layout.

**Comment by NgoHuy** [comment]
I used Fedora and had same problem, but only on XFCE not LXDE, I don't think it's problem of bogo. Did you see my config for X11 ? :v :v

**Comment by cmpitg** [comment]
Yes it is a confirmed [iBus](https://bugs.launchpad.net/ubuntu/+source/ibus/+bug/1235991) problem.  It has been on and off for quite a while now and I don't trust iBus developers anymore.  There was a similar issue reported in `ibus-unikey` repository a couple of weeks ago.

All and all, I would recommend checking and trying all possible workarounds in Arch Linux's [iBus wiki page](https://wiki.archlinux.org/index.php/IBus). As for me, I have been using `setxkbmap` (`setxkbmap us -variant dvp`) to change my keyboard layout everytime an X session starts, which works well with iBus so far.  Should you stick to this solution, you might want to have a script and make it run at startup everytime you log in.

Ha-Duong

**Comment by cmpitg** [comment]
As this is not directly related to ibus-bogo, shall we close this issue?

Ha-Duong

**Comment by cmpitg** [comment]
Closing this as there's been no further information. Feel free to re-open it anytime.
