### ISSUE TITLE
Lỗi sai từ khi gõ trong khung chat Facebook!

### ISSUE THREAD

**Issue by thangiot** [BoGoEngine/ibus-bogo#241]
Khi gõ trên khung chat của facebook, có mất dấu gạch chân bên dưới nhưng khi gõ các từ như "gõ" ở đầu câu thì nó sẽ thành "goõ"...

**Comment by vuonghv** [comment]
@thangiot Lặp với issue #233 rồi bạn.

**Comment by cmpitg** [comment]
Đóng vì lặp với #233.
