### ISSUE TITLE
Thiếu lệnh "cmake CMakeLists.txt" trong hướng dẫn cài đặt trên Ubuntu/Debian

### ISSUE THREAD

**Issue by phuctv95** [BoGoEngine/ibus-bogo#243]
Trong [hướng dẫn cài đặt](https://github.com/BoGoEngine/ibus-bogo/blob/master/doc/sphinx/install.rst), phần hướng dẫn cài đặt từ mã nguồn cho hệ điều hành **Ubuntu/Debian**, đến bước tải mã nguồn, nếu chọn tải mã nguồn v0.4 tại link https://github.com/BoGoEngine/ibus-bogo-python/releases thay vì dùng lệnh git clone về, thì khi làm đến lệnh `sudo make install` sẽ báo lỗi:
```
make: *** No rule to make target 'install'.  Stop.
```

Mình không rành lắm về cmake hay makefiles, nhưng nhớ mang máng và thử chạy lệnh `cmake CMakeLists.txt` rồi mới chạy lệnh `sudo make install` thì mọi chuyện diễn ra tốt đẹp.

Trong trường hợp tải mã nguồn về qua git clone thì quá trình cài đặt không có lỗi gì cả.

Mong các bạn cập nhật lại bài hướng dẫn cài đặt ở phần này cho hoàn chỉnh hơn :smile: 

Thông tin thêm: mình test trên Lubuntu 16.04 LTS 64bit, ibus-bogo 0.4.

**Comment by cmpitg** [comment]
Cảm ơn bạn. Mình đã cập nhật hướng dẫn :-).
