### ISSUE TITLE
Không nên gõ tiếng Việt trong command mode của Vim

### ISSUE THREAD

**Issue by lewtds** [BoGoEngine/ibus-bogo#37]
(vấn đề này áp dụng cho cả GVim)
1. Mở Vim, vào edit mode (ấn `i`), bật bogo, gõ một đoạn bằng tiếng Việt.
2. Ấn Escape (thoát edit mode, vào command mode), ấn `dd` (xóa cả dòng) thì input context không thông báo là ngừng input nên bộ gõ vẫn nhận `dd` và tưởng là gõ `đ` -> gửi một phím `d` một phím backspace và một ký tự `đ`.

**Comment by hailoc12** [comment]
Hiện tại mình tìm thấy một cách để gõ tiếng Việt trong vim, đó là dùng keymap, mình có viết lại tại đây, hy vọng vẫn còn có ích với mọi người: https://www.danghailoc.com/post/2018-11-03_go_tieng_viet_kieu_vni/

**Comment by kiemrong08** [comment]
Một đồng đạo người China đã phát minh ra công cụ này :)). Khi vào insert mode thì bật IBUS, khi trở về normal mode thì tắt IBUS. Các bác thử dùng xem

https://github.com/h-youhei/vim-ibus

**Comment by thewalldao** [comment]
> Một đồng đạo người China đã phát minh ra công cụ này :)). Khi vào insert mode thì bật IBUS, khi trở về normal mode thì tắt IBUS. Các bác thử dùng xem
> 
> https://github.com/h-youhei/vim-ibus

bác có thể chỉ cách được không , mình làm hoài mà cài không được , mình sử dụng spacevim
